### ISSUE TITLE
Deploy to GH pages and setup GH Actions for CI

### ISSUE THREAD

**Issue by toreylittlefield** [TeamPetPoison/pet-poison-alert#51]
## Tasks
- [x] build Next.js app in GH actions
- [x] deploy build to GH Pages
- [x] setup basic CI and branch protections

## Resources
- https://github.com/TeamPetPoison/pet-poison-alert/actions/new?category=none&query=next
- https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching
