### ISSUE TITLE
Add the Location Marker in Map 

### ISSUE THREAD

**Issue by toreylittlefield** [TeamPetPoison/pet-poison-alert#56]
The map needs a location marker (pin) that should be distinguishable from other map markers. This marker should be moved when the user updates the search or allows the app to access their location data.

Use something like google maps for inspiration in terms of when and how the marker shows up but let's keep it simple for now

## Tasks
- [ ] show a custom marker to indicate the selected or searched location from the user
- [ ] update marker if the user searches and selects a new location
- [ ] allow the marker to be dragged or moved by the user. Should also update the location state in the main store for `lat` `lng`?
- [ ] marker should be easy to distinguish from other markers on the app and should be allowed to be hidden
